// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6ze7JiVLYvdrcACcRuJ0tr-lAq2wnQg',
    appId: '1:630113951341:web:db3f2997104b30d2cce964',
    messagingSenderId: '630113951341',
    projectId: 'fasum-ed12b',
    authDomain: 'fasum-ed12b.firebaseapp.com',
    storageBucket: 'fasum-ed12b.appspot.com',
    measurementId: 'G-PQJ1TTND2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXQa5StxL8DENLkeNYQkewPPgwNwG_25Y',
    appId: '1:630113951341:android:1d5f8311c39919decce964',
    messagingSenderId: '630113951341',
    projectId: 'fasum-ed12b',
    storageBucket: 'fasum-ed12b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdMXhJC8nuUcPuO7WMgpkxMh5FOkMfA1w',
    appId: '1:630113951341:ios:21a02c59fcaf26b5cce964',
    messagingSenderId: '630113951341',
    projectId: 'fasum-ed12b',
    storageBucket: 'fasum-ed12b.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdMXhJC8nuUcPuO7WMgpkxMh5FOkMfA1w',
    appId: '1:630113951341:ios:21a02c59fcaf26b5cce964',
    messagingSenderId: '630113951341',
    projectId: 'fasum-ed12b',
    storageBucket: 'fasum-ed12b.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM6ze7JiVLYvdrcACcRuJ0tr-lAq2wnQg',
    appId: '1:630113951341:web:c16e5b33e3a2d105cce964',
    messagingSenderId: '630113951341',
    projectId: 'fasum-ed12b',
    authDomain: 'fasum-ed12b.firebaseapp.com',
    storageBucket: 'fasum-ed12b.appspot.com',
    measurementId: 'G-R1DMNQPMPR',
  );
}
